name: qalculate
title: Qalculate!
version: '5.1.0'
license: GPL-2.0+
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
  to use but provides power and versatility normally reserved for complicated
  math packages, as well as useful tools for everyday needs (such as currency
  conversion and percent calculation). Features include a large library of
  customizable functions, unit calculations and conversion, physical constants,
  symbolic calculations (including integrals and equations), arbitrary precision,
  uncertainty propagation, interval arithmetic, plotting, and a user-friendly
  interface.

grade: stable
confinement: strict
base: core20

compression: lzo

slots:
  dbus-qalculate:
    interface: dbus
    name: io.github.Qalculate
    bus: session

apps:
  qalc:
    environment:
        GNUPLOT_DRIVER_DIR: $SNAP/usr/libexec/gnuplot/5.2
    command: usr/bin/qalc
    extensions: [gnome-3-38]
    plugs: [network, home, removable-media]
  qalculate:
    environment:
        GNUPLOT_DRIVER_DIR: $SNAP/usr/libexec/gnuplot/5.2
    command: usr/bin/qalculate-gtk
    extensions: [gnome-3-38]
    plugs: [unity7, gsettings, network, home, removable-media]
  gtk:  # old variant of the above
    environment:
        GNUPLOT_DRIVER_DIR: $SNAP/usr/libexec/gnuplot/5.2
    command: usr/bin/qalculate-gtk
    extensions: [gnome-3-38]
    plugs: [unity7, gsettings, network, home, removable-media]
  gnuplot:
    environment:
        GNUPLOT_DRIVER_DIR: $SNAP/usr/libexec/gnuplot/5.2
    command: usr/bin/gnuplot
    extensions: [gnome-3-38]
    plugs: [unity7, gsettings, home, removable-media]

parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: v5.1.0
    source-depth: 1
    plugin: autotools
    build-environment:
      - CXXFLAGS: "$CXXFLAGS -fsigned-char"
    autotools-configure-parameters:
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    stage-packages:
      - libasn1-8-heimdal
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libwind0-heimdal
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - intltool
      - doxygen
    override-build: |
      for p in $SNAPCRAFT_PROJECT_DIR/patches/lib/*.patch
      do
        cat $p | patch -p1
      done
      ./autogen.sh
      snapcraftctl build
      echo Stripping qalc
      strip $SNAPCRAFT_PART_INSTALL/usr/bin/qalc
    after:
      - patches
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-gtk:
    source: https://github.com/Qalculate/qalculate-gtk.git
    source-tag: v5.1.0
    source-depth: 1
    plugin: autotools
    build-environment:
      - CXXFLAGS: "$CXXFLAGS -fsigned-char"
    autotools-configure-parameters:
      - --with-webkitgtk
      - --disable-gnome-search
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    stage-packages:
      - libasn1-8-heimdal
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libwind0-heimdal
    build-packages:
      - libgmp-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libxml2-dev
      - intltool
    override-build: |
      for p in $SNAPCRAFT_PROJECT_DIR/patches/gui/*.patch
      do
        cat $p | patch -p1
      done
      ./autogen.sh
      snapcraftctl build
      echo Stripping qalculate-gtk
      strip $SNAPCRAFT_PART_INSTALL/usr/bin/qalculate-gtk
    after:
      - libqalculate
      - patches
    prime:
      - -share/applications

  gnuplot:
    source: https://sourceforge.net/projects/gnuplot/files/gnuplot/5.2.8/gnuplot-5.2.8.tar.gz
    source-checksum: sha512/513dff15236dcb58c3c5471cdaa0713242787dbf30ef860c3f69152cb87c6392e4973caff5eb178707bbb84c78548e806b2920864a37686bce49425fbfdc4e8c
    plugin: autotools
    autotools-configure-parameters:
      - --without-gd
      - --without-libcerf
      - --without-linux-vga
      - --without-lua
      - --without-qt
      - --with-readline=gnu
      - --enable-wxwidgets
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    build-packages:
      - libcairo2-dev
      - libpango1.0-dev
      - libpng-dev
      - libx11-dev
      - libxt-dev
      - pkg-config
      - zlib1g-dev
    after:
      - wxwidgets-sdk
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    override-build: |
      snapcraftctl build
      echo Stripping gnuplot
      strip $SNAPCRAFT_PART_INSTALL/usr/bin/gnuplot
      strip $SNAPCRAFT_PART_INSTALL/usr/libexec/gnuplot/5.2/gnuplot_x11

  wxwidgets-sdk:
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5.1/wxWidgets-3.0.5.1.tar.bz2
    source-checksum: sha512/0a789fc5e71d414e43f75b5c16076fe8b1bcd7671be0770e4269dcef66d830c1bc74e183f49db270b928862f13472666c283fe2aa98b9006681722e06100725d
    plugin: autotools
    autotools-configure-parameters:
      - --enable-shared
      - --disable-static
      - --disable-aui
      - --disable-gstreamer8
      - --disable-html
      - --disable-htmphelp
      - --disable-mdi
      - --disable-mediactrl
      - --disable-propgrid
      - --disable-ribbon
      - --disable-richtext
      - --disable-stc
      - --disable-webkit
      - --disable-webview
      - --disable-xrc
      - --enable-unicode
      - --with-gtk=3
      - --without-opengl
      - --with-libjpeg
      - --with-libpng
      - --with-zlib
      - --prefix=/usr
    organize:
      snap/qalculate/current/usr: usr
    filesets:
      autoconf-macros:
        - usr/share/aclocal
      bakefiles:
        - usr/share/bakefile
      copyright:
        - usr/share/doc/*/copyright
      executables:
        - usr/bin
        - usr/lib/wx/config
      library-headers:
        - usr/include
      library-shared:
        - lib/*.so*
        - lib/*/*.so*
        - usr/lib/*.so*
        - usr/lib/*/*.so*
      library-static:
        - usr/lib/**.a
      localizations:
        - usr/share/locale
      misc:
        - usr/bin/*addr2line
    build-packages:
      - gcc
      - g++
      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    override-build: |
      set \
        -o errexit \
        -o nounset;
      snapcraftctl build;
      # Fix-up wx-config link
      ln \
        --force \
        --relative \
        --symbolic \
        "${SNAPCRAFT_PART_INSTALL}"/usr/lib/wx/config/* \
        "${SNAPCRAFT_PART_INSTALL}"/usr/bin/wx-config;
      # Fix-up installation prefix
      # command line - How to use sed to replace only the first occurrence in a file? - Stack Overflow
      # https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file
      sed \
        --follow-symlinks \
        --in-place \
        "0,/^prefix=.*\$/ s##prefix=\"${SNAPCRAFT_STAGE}\"/usr#" \
        "${SNAPCRAFT_PART_INSTALL}"/usr/bin/wx-config;
    prime:
      - $copyright
      - $library-shared
      - $misc

  patches:
    source: patches
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*

